title:             笔耕不辍
email:             haumonfleau@hotmail.com
description:       专注效率，成长
author:            周巧鸽
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "localhost:4000"
# url:               "http://blackrockdigital.github.io"

# Social Profiles

github_username:   juliettezhou


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
